from django.conf.urls.defaults import *


urlpatterns = patterns('',  
  url(r'^genres/(?P<slug>[-\w]+)/$',
    view    = 'basic.music.views.genre_detail',
    name    = 'music_genre_detail',
  ),
  url (r'^genres/$',
    view    = 'basic.music.views.genre_list',
    name    = 'music_genre_list',
  ),
  url(r'^labels/(?P<slug>[-\w]+)/$',
    view    = 'basic.music.views.label_detail',
    name    = 'music_label_detail',
  ),
  url (r'^labels/$',
    view    = 'basic.music.views.label_list',
    name    = 'music_label_list',
  ),
  url(r'^bands/(?P<slug>[-\w]+)/$',
    view    = 'basic.music.views.band_detail',
    name    = 'music_band_detail',
  ),
  url (r'^bands/$',
    view    = 'basic.music.views.band_list',
    name    = 'music_band_list',
  ),
  url(r'^albums/(?P<slug>[-\w]+)/$',
    view    = 'basic.music.views.album_detail',
    name    = 'music_album_detail',
  ),
  url (r'^albums/$',
    view    = 'basic.music.views.album_list',
    name    = 'music_album_list',
  ),
  url(r'^tracks/(?P<slug>[-\w]+)/$',
    view    = 'basic.music.views.track_detail',
    name    = 'music_track_detail',
  ),
  url (r'^tracks/$',
    view    = 'basic.music.views.track_list',
    name    = 'music_track_list',
  ),
  url (r'^$',
    view    = 'django.views.generic.simple.direct_to_template',
    kwargs  = {'template': 'music/index.html'},
    name    = 'music_index',
  ),
)