from django.conf.urls.defaults import *


urlpatterns = patterns('basic.music.views',
    url(r'^genres/(?P<slug>[-\w]+)/$',
        view='genre_detail',
        name='music_genre_detail',
    ),
    url (r'^genres/$',
        view='genre_list',
        name='music_genre_list',
    ),
    url(r'^labels/(?P<slug>[-\w]+)/$',
        view='label_detail',
        name='music_label_detail',
    ),
    url (r'^labels/$',
        view='label_list',
        name='music_label_list',
    ),
    url(r'^bands/(?P<slug>[-\w]+)/$',
        view='band_detail',
        name='music_band_detail',
    ),
    url (r'^bands/$',
        view='band_list',
        name='music_band_list',
    ),
    url(r'^albums/(?P<slug>[-\w]+)/$',
        view='album_detail',
        name='music_album_detail',
    ),
    url (r'^albums/$',
        view='album_list',
        name='music_album_list',
    ),
    url(r'^tracks/(?P<slug>[-\w]+)/$',
        view='track_detail',
        name='music_track_detail',
    ),
    url (r'^tracks/$',
        view='track_list',
        name='music_track_list',
    ),
)


urlpatterns += patterns('',
    url (r'^$',
        view='django.views.generic.simple.direct_to_template',
        kwargs={'template': 'music/index.html'},
        name='music_index',
    ),
)